In [15]:
# Only using numpy to create arrays, no other functions from numpy used
import numpy as np
# Define 2x2 array
A = np.array([[-5, 2], [-7, 4]])

# Other arrays to prove this code works for multiple inputs
# A = np.array([[1, 2], [3, 4]])
# A = np.array([[47, 120], [-18, -46]])

# Define 2x2 identity matrix
I = np.array([[1, 0], [0, 1]])

# Check if array is square
if A.shape[0] != A.shape[1]:
  print('Array is not square')
else:
  print('Array is square')
print('The array is: ', A)
print('~~~~~')

# ===========================================================================

# QUESTION 1a
# Compute eigenvalues of square array

# To find eigenvalue: A@X - lamda*X = 0, therefore det(lamba*I - A) = 0

# Define lamda as some large negative starting number L1 and (lamda*I - A) as
# some variable A1
L1 = -100
A1 = (L1*I - A)

# Variable to iterate within loops, can be decreased for accuracy
iter = 0.0001

# Find determinant of A1
det_A1 = (A1[0,0]*A1[1,1])-(A1[0,1]*A1[1,0])

# Round determinant to three decimal places for simplicity, can be increased
det_A1_round = round(det_A1, 3)

# Iterate on L1 until det_A1 == 0, which will return first eigenvalue counting
# up from L1's inital value (-100 in this case, can be larger)
while det_A1_round != 0:
  L1 += iter
  A1 = (L1*I - A)
  det_A1 = (A1[0,0]*A1[1,1])-(A1[0,1]*A1[1,0])
  det_A1_round = round(det_A1, 3)

# Returns the first eigenvalue L1, rounded to four decimal places
L1_round = round(L1, 4)
L1_round0 = round(L1, 0)
diff = 0.0001
L1_diff1 = L1_round + diff
L1_diff2 = L1_round - diff

# Decides to round L1, depending on if it is very close to a whole number
if L1_diff1 == L1_round0:
  print('The first eigenvalue is: ',L1_round0)
elif L1_diff2 == L1_round0:
  print('The first eigenvalue is: ',L1_round0)
else:
  print('The first eigenvalue is: ',L1_round)
print('~~~~~')

# Now to find next eigenvalue after L1, define L2 as L1 + 0.1, and continue
L2 = L1 + 0.1
A2 = (L2*I - A)

# Find determinant of A2, rounding same as above
det_A2 = (A2[0,0]*A2[1,1])-(A2[0,1]*A2[1,0])
det_A2_round = round(det_A2, 3)

# Iterate on L2, same as above on L1, but starts just above L1 (0.1 more)
while det_A2_round != 0:
  L2 += iter
  A2 = (L2*I - A)
  det_A2 = (A2[0,0]*A2[1,1])-(A2[0,1]*A2[1,0])
  det_A2_round = round(det_A2, 3)

# Returns the second eigenvalue L2, also rounded to four decimal places
L2_round = round(L2, 4)
L2_round0 = round(L2, 0)
diff = 0.0001
L2_diff1 = L2_round + diff
L2_diff2 = L2_round - diff

# Decides to round L2, depending on if it is very close to a whole number
if L2_diff1 == L2_round0:
  print('The second eigenvalue is: ',L2_round0)
elif L2_diff2 == L2_round0:
  print('The second eigenvalue is: ',L2_round0)
else:
  print('The second eigenvalue is: ',L2_round)
print('~~~~~')

# This can continue for third eigenvalue for 3x3 array, fourth eigenvalue for
# 4x4 array, etc.
# You just have to change the calculation for determinant to match array size,
# add L3, L4, change identity array I to 3x3, 4x4, etc.

# ===========================================================================

# QUESTION 1b
# Determine eigenvectors for all eigenvalues

# Solve for [A-L1*I][x] = [0] and [A-L2*I][x] = [0]
# Apply vector multiplication, get system of 2 eqs w/ 2 vars that both = 0

# Define xa as array with large starting value x1 = 100, and x2 in terms of x1
# using the above system of equations
x1 = 100
x2 = (-(A[1,0]-L1*I[1,0])*x1)/(A[1,1]-L1*I[1,1])

# Substitute x2 into x1... = 0 equation using L1
limit = (A[0,0]-L1*I[0,0])*x1 + (A[0,1]-L1*I[0,1])*(x2)
limit_round = round(limit, 3)

# Iterate on x1 the same as was done above working your way down to a solution
while limit_round != 0:
  x1 -= iter
  x2 = (-(A[1,0]-L1*I[1,0])*x1)/(A[1,1]-L1*I[1,1])
  limit = (A[0,0]-L1*I[0,0])*x1 + (A[0,1]-L1*I[0,1])*(x2)
  limit_round = round(limit, 3)

# Create array with solutions for x1, x2
x1_round = round(x1, 4)
x1_round0 = round(x1,0)
x2_round = round(x2, 4)
x2_round0 = round(x2,0)
diff = 0.0001

x1_diff1 = x1_round + diff
x1_diff2 = x1_round - diff
x2_diff1 = x2_round + diff
x2_diff2 = x2_round - diff

# Decides to round x1, x2, depending on if it is very close to a whole number
if x1_diff1 == x1_round0:
  x1_round = x1_round0
elif x1_diff2 == x1_round0:
  x1_round = x1_round0
else:
  x1_round = x1_round

if x2_diff1 == x2_round0:
  x2_round = x2_round0
elif x2_diff2 == x2_round0:
  x2_round = x2_round0
else:
  x2_round = x2_round

# Outputs eigenvectors under different rounding conditions (whole/decimal)
xa = np.array([[x1_round], [x2_round]],dtype=float)

if L1_diff1 == L1_round0:
  print('The eigenvector for: ',L1_round0,'is: ',xa)
elif L1_diff2 == L1_round0:
  print('The eigenvector for: ',L1_round0,'is: ',xa)
else:
  print('The eigenvector for: ',L1_round,'is: ',xa)
print('~~~~~')

# Repeat for L2, with new x values xb = [[x3], [x4]]
x3 = 100
x4 = (-(A[1,0]-L2*I[1,0])*x3)/(A[1,1]-L2*I[1,1])

limit2 = (A[0,0]-L2*I[0,0])*x3 + (A[0,1]-L2*I[0,1])*(x4)
limit_round2 = round(limit2, 3)

while limit_round2 != 0:
  x3 -= iter
  x4 = (-(A[1,0]-L2*I[1,0])*x3)/(A[1,1]-L2*I[1,1])
  limit2 = (A[0,0]-L2*I[0,0])*x3 + (A[0,1]-L2*I[0,1])*(x4)
  limit_round2 = round(limit2, 3)


# Create array with solutions for x3, x4
x3_round = round(x3, 4)
x3_round0 = round(x3,0)
x4_round = round(x4, 4)
x4_round0 = round(x4,0)
diff = 0.0001

x3_diff1 = x3_round + diff
x3_diff2 = x3_round - diff
x4_diff1 = x4_round + diff
x4_diff2 = x4_round - diff

# Decides to round x1, x2, depending on if it is very close to a whole number
if x3_diff1 == x3_round0:
  x3_round = x3_round0
elif x3_diff2 == x3_round0:
  x3_round = x3_round0
else:
  x3_round = x3_round

if x4_diff1 == x4_round0:
  x4_round = x4_round0
elif x4_diff2 == x4_round0:
  x4_round = x4_round0
else:
  x4_round = x4_round

# Outputs eigenvectors under different rounding conditions (whole/decimal)
xb = np.array([[x3_round], [x4_round]],dtype=float)

if L2_diff1 == L2_round0:
  print('The eigenvector for: ',L2_round0,'is: ',xb)
elif L2_diff2 == L2_round0:
  print('The eigenvector for: ',L2_round0,'is: ',xb)
else:
  print('The eigenvector for: ',L2_round,'is: ',xb)


Array is square
The array is:  [[-5  2]
 [-7  4]]
~~~~~
The first eigenvalue is:  -3.0
~~~~~
The second eigenvalue is:  2.0
~~~~~
The eigenvector for:  -3.0 is:  [[7.]
 [7.]]
~~~~~
The eigenvector for:  2.0 is:  [[2.]
 [7.]]


In [16]:
# QUESTION 2
# Compute factor of array by Singlular Value Decomposition
# Can be written as A*V = U*E or A = U*E*V_T

# Only using numpy to create original arrays, no other functions used
import numpy as np

A = np.array([[5, 5], [-1, 7]])

# Setup empty U, E, V arrays
U = np.array([[0, 0], [0, 0]],dtype=float)
E = np.array([[0, 0], [0, 0]],dtype=float)
V = np.array([[0, 0], [0, 0]],dtype=float)

# Setup empty transpose array to be populated
A_T = np.array([[0, 0], [0, 0]],dtype=float)

for i in range(len(A)):
  for j in range(len(A[0])):
    A_T[j][i] = A[i][j]

A_eig = A_T@A

print('The result of A(transpose) * A is: ')
print(A_eig)

# Find eigenvalues of A_T@A using same method as question 1

I = np.array([[1, 0], [0, 1]])

# Define lamda as some large negative starting number L1 and (lamda*I - A_eig)
# as some variable A_eig1
L1 = -100
iter = 0.01
A_eig1 = (L1*I - A_eig)

# Find determinant of A_T@A
det_A_eig1 = (A_eig1[0,0]*A_eig1[1,1])-(A_eig1[0,1]*A_eig1[1,0])

# Round determinant to one decimal place for simplicity, can be increased if
# using more computing power
det_A_eig1_round = round(det_A_eig1, 1)

# Iterate on L1 until det_A_eig1 == 0, which will return first eigenvalue
# counting down from L1's inital value (100 in this case, can be larger)
while det_A_eig1_round != 0:
  L1 += iter
  A_eig1 = (L1*I - A_eig)
  det_A_eig1 = (A_eig1[0,0]*A_eig1[1,1])-(A_eig1[0,1]*A_eig1[1,0])
  det_A_eig1_round = round(det_A_eig1, 1)

L1_round = round(L1, 2)
L1_round0 = round(L1, 0)
diff = 0.0001
L1_diff1 = L1_round + diff
L1_diff2 = L1_round - diff

if L1_diff1 == L1_round0:
  print('The first eigenvalue of A(transpose) * A is: ',L1_round0)
elif L1_diff2 == L1_round0:
  print('The first eigenvalue of A(transpose) * A is: ',L1_round0)
else:
  print('The first eigenvalue of A(transpose) * A is: ',L1_round)
print('~~~~~')

# Now to find next eigenvalue after L1, define L2 as L1 + 0.1, and continue
L2 = L1 + 0.1
A_eig2 = (L2*I - A_eig)

# Find determinant of A_eig2, rounding same as above
det_A_eig2 = (A_eig2[0,0]*A_eig2[1,1])-(A_eig2[0,1]*A_eig2[1,0])
det_A_eig2_round = round(det_A_eig2, 1)

# Iterate on L2, same as above on L1, but starts just above L1 (0.1 more)
while det_A_eig2_round != 0:
  L2 += iter
  A_eig2 = (L2*I - A_eig)
  det_A_eig2 = (A_eig2[0,0]*A_eig2[1,1])-(A_eig2[0,1]*A_eig2[1,0])
  det_A_eig2_round = round(det_A_eig2, 1)

# Returns the second eigenvalue L2, also rounded to four decimal places
L2_round = round(L2, 4)
L2_round0 = round(L2, 0)
diff = 0.0001
L2_diff1 = L2_round + diff
L2_diff2 = L2_round - diff

if L2_diff1 == L2_round0:
  print('The second eigenvalue is: ',L2_round0)
elif L2_diff2 == L2_round0:
  print('The second eigenvalue is: ',L2_round0)
else:
  print('The second eigenvalue is: ',L2_round)
print('~~~~~')


sigma1 = (L1)**.5
sigma1_round = round(sigma1,2)
sigma2 = (L2)**.5
sigma2_round = round(sigma2,2)

print('The first sigma for E is: ',sigma1_round)
print('The second sigma for E is: ',sigma2_round)

E[0,0] = sigma1_round
E[1,1] = sigma2_round

# Output the array E for the equation A = U * E * V_T
print('The array E is: ')
print(E)
print('~~~~~')

# This can continue for third eigenvalue for 3x3 array, fourth eigenvalue for
# 4x4 array, etc.
# You just have to change the calculation for determinant to match array size

# ===========================================================================

# Determine array V_T for the equation A = U * E * V_T
# DETERMINE EIGENVECTORS FOR ALL EIGENVALUES of A_T*A

# Solve for [(A_T*A)-L1*I][v] = [0] and [(A_T*A)-L2*I][v] = [0]
# Apply vector multiplication, get system of 2 eqs w/ 2 vars that both = 0

# Define va as array with large starting value v1 = -100, v2 in terms of v1
# using the above system of equations
v1 = -100
v2 = (-(A_eig[1,0]-L1*I[1,0])*v1)/(A_eig[1,1]-L1*I[1,1])

# Substitute v2 into v1... = 0 equation using L1
limit = (A_eig[0,0]-L1*I[0,0])*v1 + (A_eig[0,1]-L1*I[0,1])*(v2)
limit_round = round(limit, 3)

# Iterate on v1 the same as was done above working your way down to a solution
while limit_round != 0:
  v1 += iter
  v2 = (-(A_eig[1,0]-L1*I[1,0])*v1)/(A_eig[1,1]-L1*I[1,1])
  limit = (A_eig[0,0]-L1*I[0,0])*v1 + (A_eig[0,1]-L1*I[0,1])*(v2)
  limit_round = round(limit, 3)

# Create array with solutions for v1, v2
v1_round = round(v1, 4)
v1_round0 = round(v1,0)
v2_round = round(v2, 4)
v2_round0 = round(v2,0)
diff = 0.0001

v1_diff1 = v1_round + diff
v1_diff2 = v1_round - diff
v2_diff1 = v2_round + diff
v2_diff2 = v2_round - diff

if v1_diff1 == v1_round0:
  v1_round = v1_round0
elif v1_diff2 == v1_round0:
  v1_round = v1_round0
else:
  v1_round = v1_round

if v2_diff1 == v2_round0:
  v2_round = v2_round0
elif v2_diff2 == v2_round0:
  v2_round = v2_round0
else:
  v2_round = v2_round

# Outputs eigenvectors under different rounding conditions (whole/decimal)

Va = np.array([[v1_round], [v2_round]],dtype=float)

# Normalize vector by dividing by sqrt of sum of squares
Va_denom = (v1**2 + v2**2)**.5
Va_N = np.array([[round(v1/Va_denom,4)], [round(v2/Va_denom,4)]],dtype=float)

if L1_diff1 == L1_round0:
  print('The normalized eigenvector of A(transpose) * A for: ',L1_round0,'is: ')
  print(Va_N)
elif L1_diff2 == L1_round0:
  print('The normalized eigenvector of A(transpose) * A for: ',L1_round0,'is: ')
  print(Va_N)
else:
  print('The normalized eigenvector of A(transpose) * A for: ',L1_round,'is: ')
  print(Va_N)
print('~~~~~')

# Repeat for L2, with new v values Vb = [[v3], [v4]]
v3 = -100
v4 = (-(A_eig[1,0]-L2*I[1,0])*v3)/(A_eig[1,1]-L2*I[1,1])

limit2 = (A_eig[0,0]-L2*I[0,0])*v3 + (A_eig[0,1]-L2*I[0,1])*(v4)
limit_round2 = round(limit2, 3)

while limit_round2 != 0:
  v3 += iter
  v4 = (-(A_eig[1,0]-L2*I[1,0])*v3)/(A_eig[1,1]-L2*I[1,1])
  limit2 = (A_eig[0,0]-L2*I[0,0])*v3 + (A_eig[0,1]-L2*I[0,1])*(v4)
  limit_round2 = round(limit2, 3)


# Create array with solutions for v3, v4
v3_round = round(v3, 4)
v3_round0 = round(v3,0)
v4_round = round(v4, 4)
v4_round0 = round(v4,0)
diff = 0.0001

v3_diff1 = v3_round + diff
v3_diff2 = v3_round - diff
v4_diff1 = v4_round + diff
v4_diff2 = v4_round - diff

if v3_diff1 == v3_round0:
  v3_round = v3_round0
elif v3_diff2 == v3_round0:
  v3_round = v3_round0
else:
  v3_round = v3_round

if v4_diff1 == v4_round0:
  v4_round = v4_round0
elif v4_diff2 == v4_round0:
  v4_round = v4_round0
else:
  v4_round = v4_round

# Outputs eigenvectors under different rounding conditions (whole/decimal)

Vb = np.array([[v3_round], [v4_round]],dtype=float)

# Normalize vector by dividing by sqrt of sum of squares
Vb_denom = (v3**2 + v4**2)**.5
Vb_N = np.array([[round(v3/Vb_denom,4)], [round(v4/Vb_denom,4)]],dtype=float)

if L2_diff1 == L2_round0:
  print('The normalized eigenvector of A(transpose) * A for: ',L2_round0,'is: ')
  print(Vb_N)
elif L2_diff2 == L2_round0:
  print('The normalized eigenvector of A(transpose) * A for: ',L2_round0,'is: ')
  print(Vb_N)
else:
  print('The normalized eigenvector of A(transpose) * A for: ',L2_round,'is: ')
  print(Vb_N)
print('~~~~~')

v_denom = (v1**2+v2**2+v3**2+v4**2)**0.5

V[0,0] = v1/v_denom
V[0,1] = v2/v_denom
V[1,0] = v3/v_denom
V[1,1] = v4/v_denom

# Setup empty transpose array to be populated
V_T = np.array([[0, 0], [0, 0]],dtype=float)

for i in range(len(V)):
  for j in range(len(V[0])):
    V_T[j][i] = V[i][j]

# Output the array V(transpose) for the equation A = U * E * V_T
print('The array V(transpose) is: ')
print(V_T)
print('~~~~~')

# ===========================================================================

# Determine array U for the equation A = U * E * V_T
# Find U = [[u1], [u2]] using:
# u1 = 1/sigma1 * A @ Va_N  AND  u2 = 1/sigma2 * A @ Vb_N

u1 = (1/sigma1)*A@Va_N
u2 = (1/sigma2)*A@Vb_N

U = np.array([[u1], [u2]],dtype=float)

# Output the array U for the equation A = U * E * V_T
print('The array U is: ')
print(U)
print('~~~~~')

print('Therefore the Singular Value Decomposition of the form A=U*E*V_T is: ')
print(A,' = ',U,' * ',E,' * ',V_T)

The result of A(transpose) * A is: 
[[26. 18.]
 [18. 74.]]
The first eigenvalue of A(transpose) * A is:  20.0
~~~~~
The second eigenvalue is:  80.0
~~~~~
The first sigma for E is:  4.47
The second sigma for E is:  8.94
The array E is: 
[[4.47 0.  ]
 [0.   8.94]]
~~~~~
The normalized eigenvector of A(transpose) * A for:  20.0 is: 
[[-0.9487]
 [ 0.3162]]
~~~~~
The normalized eigenvector of A(transpose) * A for:  80.0 is: 
[[-0.3162]
 [-0.9487]]
~~~~~
The array V(transpose) is: 
[[-0.3 -0.3]
 [ 0.1 -0.9]]
~~~~~
The array U is: 
[[[[-0.7071565 ]
   [ 0.70706706]]]


 [[[-0.7071006 ]
   [-0.70712296]]]]
~~~~~
Therefore the Singular Value Decomposition of the form A=U*E*V_T is: 
[[ 5  5]
 [-1  7]]  =  [[[[-0.7071565 ]
   [ 0.70706706]]]


 [[[-0.7071006 ]
   [-0.70712296]]]]  *  [[4.47 0.  ]
 [0.   8.94]]  *  [[-0.3 -0.3]
 [ 0.1 -0.9]]


In [17]:
# QUESTION 3
# Find the determinant of an array

# Will use the same method as above for a 2x2 matrix where
# det(A) = A[0,0]*A[1,1]-A[0,1]*A[1,0]

# Only using numpy to create arrays, no other functions used
import numpy as np
# Define 2x2 array
A = np.array([[-5, 2], [-7, 4]])

# Other arrays to prove this code works for multiple inputs
# A = np.array([[1, 2], [3, 4]])
# A = np.array([[47, 120], [-18, -46]])

# Check if array is square
if A.shape[0] != A.shape[1]:
  print('Array is not square, and does not have eigenvalues')
else:
  print('Array is square')
print('~~~~~')

# Find determinant of A using above formula
det_A = (A[0,0]*A[1,1])-(A[0,1]*A[1,0])

print('The determinant of array A = ',A,' is: ',det_A)

Array is square
~~~~~
The determinant of array A =  [[-5  2]
 [-7  4]]  is:  -6
